#!/usr/bin/env bash
#MISE description="Run yucca-api in development mode"
#MISE depends=["common:build"]
#MISE dir="{{config_root}}"
set -e
source "$(dirname "$0")/env"

op run --env-file="./.env" -- pnpm --filter yucca-api start:dev
