#!/usr/bin/env bash
#MISE description="Run yucca-api in development mode"
#MISE depends=["common:build"]
#MISE dir="{{config_root}}"
set -e
source "$(dirname "$0")/env"

if command -v op &>/dev/null; then
  op run --env-file="./.env" -- pnpm --filter yucca-api start:dev
else
  pnpm --filter yucca-api start:dev
fi
