#!/usr/bin/env bash
#MISE description="Build standalone-app"
#MISE depends=["yucca-sdk:orchestration-api:build", "yucca-sdk:orchestration-ui:build"]
set -e

NODE_ENV=production pnpm --filter @futo-org/backups-standalone build
