#!/usr/bin/env bash
# Render the o11y bundle into <output-dir>: dashboards/*.json -> GrafanaDashboard
# CRs (gzip+base64 spec.gzipJson) under one GrafanaFolder; alerts (already
# GrafanaAlertRuleGroup CRs) copied verbatim. CI pushes the bundle as an OCI
# artifact; o11y applies it via Flux OCIRepository + Kustomization (no
# kustomization.yaml — kustomize-controller generates one). o11y/ is the source
# of truth; this output is build product, never committed. See o11y/README.md.
set -euo pipefail

usage='usage: render-o11y-manifests.sh <output-dir> <github-repository>'
out=${1:?$usage}
repo=${2:?$usage} # owner/name, e.g. immich-app/yucca; stamped into the manifests
src=o11y

mkdir -p "$out/dashboards"

# All dashboards are filed under one GrafanaFolder (folderRef -> metadata.name)
# named after the repo.
folder=${repo#*/}

# The instanceSelector/resyncPeriod defaults below are o11y-overridable via
# its Flux Kustomization spec.patches.
cat >"$out/folder.yaml" <<EOF
# generated by https://github.com/${repo}; do not edit
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: ${folder}
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  resyncPeriod: 10m
  title: ${folder}
EOF

dashboards=0
for f in "$src"/dashboards/*.json; do
  # file name, .uid, and metadata.name must agree on one DNS-1123 name that
  # doesn't collide with the bundle's own files.
  uid=$(basename "$f" .json)
  if [ "$(jq -r .uid "$f")" != "$uid" ] || [ "$uid" = folder ] || [ "$uid" = kustomization ] ||
    ! printf '%s' "$uid" | grep -Eq '^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$'; then
    echo "$f: uid must be a DNS-1123 name matching the file name, and not 'folder' or 'kustomization'" >&2
    exit 1
  fi
  # gzip -n: drop name/mtime so identical JSON renders byte-identical.
  # base64 | tr: portable no-wrap (BSD base64 has no -w0).
  gz=$(gzip -nc "$f" | base64 | tr -d '\n')
  cat >"$out/dashboards/${uid}.yaml" <<EOF
# generated from ${f} in https://github.com/${repo}; do not edit
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: ${uid}
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  resyncPeriod: 10m
  folderRef: ${folder}
  gzipJson: ${gz}
EOF
  dashboards=$((dashboards + 1))
done

# Alerts are authored directly as GrafanaAlertRuleGroup CRs; ship them as-is.
alerts=0
if compgen -G "$src/alerts/*.yaml" >/dev/null; then
  mkdir -p "$out/alerts"
  cp "$src"/alerts/*.yaml "$out/alerts/"
  alerts=$(compgen -G "$src/alerts/*.yaml" | wc -l | tr -d ' ')
fi

echo "rendered GrafanaFolder ${folder} + ${dashboards} dashboards + ${alerts} alert groups into ${out}"
