name: yucca-devenv

services:
  minio:
    image: quay.io/minio/minio@sha256:14cea493d9a34af32f524e538b8346cf79f3321eff8e708c1e2960462bd8936e
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID:-minio}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY:-miniominio}
      _MINIO_DRIVE_ACTIVE_MONITORING: off

  database:
    image: postgres:18@sha256:8ff36f3c66371cba71d20ceedccfc3de9669a68737607888c4ef0af93abe8e39
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: yucca
    ports:
      - 15432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d yucca']
      interval: 1s
      timeout: 5s
      retries: 30
      start_period: 10s

  mock-oidc-provider:
    build:
      context: .
      dockerfile: packages/mock-oidc-provider/Dockerfile
    ports:
      - 8092:80
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://localhost/.well-known/openid-configuration > /dev/null']
      interval: 1s
      timeout: 5s
      retries: 30
      start_period: 5s

  victoria-metrics:
    image: victoriametrics/victoria-metrics:latest@sha256:dc030542eb0cd262287c9ec32e5867f8dcccc0efd5906c10f7fc8176c53d34d7
    ports:
      - 8428:8428

  victoria-logs:
    image: docker.io/victoriametrics/victoria-logs:v1.52.0@sha256:47b820890d64c4575a2a0a46415dcd8a4fd59a0f1fcd6a377693d7aea639442e
    ports:
      - 9428:9428
    command: -storageDataPath=victoria-logs-data

  victoria-traces:
    image: docker.io/victoriametrics/victoria-traces:latest@sha256:d42615c458b5698737c33411359012a1136c3f579e4c2516687db2ea7ed08362
    ports:
      - 10428:10428
