---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs-system
  labels:
    # The localpv provisioner + helper pods need hostpath.
    pod-security.kubernetes.io/enforce: privileged
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
