#!/usr/bin/env bash
#MISE description="Run all end-to-end tests"
#MISE depends=["test:e2e:wait"]
set -e
source "$(dirname "$0")/../../michael/env"
source "$(dirname "$0")/../../yucca-api/env"

pnpm --filter e2e test "$@"
