#!/usr/bin/env bash
#MISE description="Run all end-to-end tests"
#MISE depends=["test:e2e:wait", "//packages/restic-proxy:build"]
set -e
source "$(dirname "$0")/../../michael/env"
source "$(dirname "$0")/../../../../packages/yucca-api/.mise/tasks/env"
export PATH="$(dirname "$0")/../../../../dist:$PATH"

pnpm --filter e2e test "$@"
