#!/usr/bin/env bash
#MISE description="Run all end-to-end tests"
set -e

# setup restic API server
trap "lsof -ti:$RESTIC_API_PORT | xargs kill -9 2>/dev/null || true" EXIT

mise restic-api:dev &

while ! nc -z localhost "$RESTIC_API_PORT" 2>/dev/null; do
  sleep 0.1
done

pnpm --filter e2e test
