#!/usr/bin/env bash
#MISE description="Run all end-to-end tests"
set -e

cleanup() {
  lsof -ti:$RESTIC_API_PORT | xargs kill -9 2>/dev/null || true
}

trap cleanup EXIT INT TERM

# start services
mise restic-api:dev &

while ! nc -z localhost "$RESTIC_API_PORT" 2>/dev/null; do
  sleep 0.1
done

pnpm --filter e2e test "$@"
