---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Restart chronyd
  ansible.builtin.systemd:
    name: chronyd
    state: restarted

- name: Restart sshd
  ansible.builtin.systemd:
    name: ssh
    state: restarted
