#!/usr/bin/env bash
#MISE description="Run end-to-end tests for yucca-sdk/orchestration-ui"
#MISE depends=["yucca-sdk:orchestration-ui:test:install-deps"]
set -e

# pnpm --filter orchestration-ui test:e2e "$@"
echo Currently no tests are written for Orchestration UI.
