#!/usr/bin/env bash
#MISE description="Install playwright dependencies"
set -e

if [[ -z "${PLAYWRIGHT_BROWSERS_PATH}" ]]; then
pnpm --filter @futo-org/backups-orchestrator-ui exec playwright install
fi
