apiVersion: v2
name: mock-postmark
description: Mock Postmark API for local dev (homegrown packages/mock-postmark-provider)
type: application
version: 0.1.0
appVersion: "0.0.1"
dependencies:
  - name: yucca-common
    version: 0.2.0
    repository: "file://../../lib/yucca-common"
