site_id    = 40
site_code  = "FSN1"
netbox_url = "https://netbox.futoinfra.com"

# Login users/groups now live in the central registry: shared/modules/identity.
# Add people + their SSH keys + group memberships there; fabric-mapped groups
# (e.g. fabric-admins) become login users on every VC automatically.

# cls1 (cls1netsw) leaf VC member serials.
cls1_leaf_serials = ["XH4925470753", "XH4925460012"]

# spine (corenetsw) VC member serials.
spine_vc_serials = ["WH3622440738", "WH0220510012"]

# ── mgmt-host reprovisioning (mgmt.tf) ───────────────────────────────────────
# The provisioning keypair is GENERATED by Terraform and stored in 1Password
# (op_vault, default yucca_tf_prod) as HTZ_FSN1_PROVISIONING_SSH_PRIVATE_KEY;
# ansible/mgmt reads the private half from there. Nothing to set here.

# Hosts to ARM for a fresh OS install on next boot (DESTRUCTIVE on reboot).
# Reprovisioning both mgmt nodes. NOTE: mgmt-1 is the tailscale subnet router —
# reboot mgmt-2 first and confirm it's a working route peer before rebooting
# mgmt-1, or site routing drops. Set back to [] once reprovisioning is complete.
mgmt_reprovision_targets = ["htz-fsn-mgmt-1", "htz-fsn-mgmt-2"]
