---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs-system
  labels:
    # OpenEBS localpv provisioner + helper pods run privileged (hostpath).
    pod-security.kubernetes.io/enforce: privileged
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
