---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: yucca-victoria-metrics
  namespace: yucca
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: victoria-metrics-single
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    server:
      fullnameOverride: victoria-metrics
      # TODO(prod): enable + size persistence for the target cluster.
      persistentVolume:
        enabled: false
