{
 "title": "Yucca: Hubble",
 "description": "Imported from https://raw.githubusercontent.com/cilium/cilium/v1.19.5/install/kubernetes/cilium/files/hubble/dashboards/hubble-dashboard.json by o11y/scripts/import-upstream.py; local edits are overwritten on re-import.",
 "tags": [
  "cilium",
  "imported",
  "yucca"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(hubble_flows_processed_total, cluster)"
   }
  ]
 },
 "panels": [
  { "title": "General Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Flows processed Per Node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(sum(rate(hubble_flows_processed_total[1m])) by (pod))",
     "legendFormat": "avg"
    },
    {
     "expr": "min(sum(rate(hubble_flows_processed_total[1m])) by (pod))",
     "legendFormat": "min"
    },
    {
     "expr": "max(sum(rate(hubble_flows_processed_total[1m])) by (pod))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Flows Types",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total[1m])) by (pod, type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "L7 Flow Distribution",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total{type=\"L7\", cluster=~\"$cluster\"}[1m])) by (pod, subtype)",
     "legendFormat": "{{subtype}}"
    }
   ]
  },
  {
   "title": "Trace Flow Distribution",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total{type=\"Trace\", cluster=~\"$cluster\"}[1m])) by (pod, subtype)",
     "legendFormat": "{{subtype}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Forwarded vs Dropped",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total[1m])) by (pod, verdict)",
     "legendFormat": "{{verdict}}"
    }
   ]
  },
  {
   "title": "Drop Reason",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_drop_total[1m])) by (pod, reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Protocol Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(hubble_port_distribution_total[1m])) by (pod, protocol)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Top 10 Port Distribution",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum (rate(hubble_port_distribution_total{port!=\"0\", cluster=~\"$cluster\"}[1m])) by (pod, port, protocol))",
     "legendFormat": "{{port}}/{{protocol}}"
    }
   ]
  },
  {
   "title": "TCPv4",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_tcp_flags_total{family=\"IPv4\", cluster=~\"$cluster\"}[1m])) by (pod, flag)",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "Missing TCPv4 SYN-ACKs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_tcp_flags_total{family=\"IPv4\", flag=\"SYN\", cluster=~\"$cluster\"}[1m])) by (pod) - sum(rate(hubble_tcp_flags_total{family=\"IPv4\", flag=\"SYN-ACK\", cluster=~\"$cluster\"}[1m])) by (pod)",
     "legendFormat": "Missing SYN-ACK"
    }
   ]
  },
  {
   "title": "TCPv6",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_tcp_flags_total{family=\"IPv6\", cluster=~\"$cluster\"}[1m])) by (pod, flag)",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "Missing TCPv6 SYN-ACKs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_tcp_flags_total{family=\"IPv6\", flag=\"SYN\", cluster=~\"$cluster\"}[1m])) by (pod) - sum(rate(hubble_tcp_flags_total{family=\"IPv6\", flag=\"SYN-ACK\", cluster=~\"$cluster\"}[1m])) by (pod)",
     "legendFormat": "Missing SYN-ACK"
    }
   ]
  },
  {
   "title": "ICMPv4",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_icmp_total{family=\"IPv4\", cluster=~\"$cluster\"}[1m])) by (pod, type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Missing ICMPv4 Echo-Reply",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_icmp_total{family=\"IPv4\", type=\"EchoRequest\", cluster=~\"$cluster\"}[1m])) by (pod) - sum(rate(hubble_icmp_total{family=\"IPv4\", type=\"EchoReply\", cluster=~\"$cluster\"}[1m])) by (pod)",
     "legendFormat": "Missing ICMP Echo-Reply"
    }
   ]
  },
  {
   "title": "ICMPv6",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_icmp_total{family=\"IPv6\", cluster=~\"$cluster\"}[1m])) by (pod, type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Missing ICMPv6 Echo-Reply",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_icmp_total{family=\"IPv6\", type=\"EchoRequest\", cluster=~\"$cluster\"}[1m])) by (pod) - sum(rate(hubble_icmp_total{family=\"IPv6\", type=\"EchoReply\", cluster=~\"$cluster\"}[1m])) by (pod)",
     "legendFormat": "Missing ICMP Echo-Reply"
    }
   ]
  },
  { "title": "Network Policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Denies by Reason",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_drop_total{reason=\"POLICY_DENIED\", cluster=~\"$cluster\"}[1m])) by (pod, reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Denied Packets by Protocol",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_drop_total{reason=\"POLICY_DENIED\", cluster=~\"$cluster\"}[1m])) by (pod, protocol)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Top 10 Source Pods with Denied Packets",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(hubble_drop_total{reason=\"POLICY_DENIED\", cluster=~\"$cluster\"}[1m])) by (pod, source))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Top 10 Destination Pods with Denied Packets",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(hubble_drop_total{reason=\"POLICY_DENIED\", cluster=~\"$cluster\"}[1m])) by (pod, destination))",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  { "title": "DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "DNS Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_dns_queries_total[1m])) by (pod, qtypes)",
     "legendFormat": "{{qtypes}}"
    }
   ]
  },
  {
   "title": "DNS responses",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_dns_responses_total{rcode=\"No Error\", cluster=~\"$cluster\"}[1m])) by (pod, qtypes)",
     "legendFormat": "{{qtypes}}"
    }
   ]
  },
  {
   "title": "Missing DNS Responses",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_dns_queries_total[1m])) by (pod, qtypes) - sum(rate(hubble_dns_responses_total[1m])) by (pod, qtypes)",
     "legendFormat": "{{qtypes}}"
    }
   ]
  },
  {
   "title": "DNS Response Record Type",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_dns_response_types_total[1m])) by (pod, type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "DNS Response IPs Returned",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_dns_responses_total{rcode=\"No Error\", cluster=~\"$cluster\"}[1m])) by (pod,ips_returned)",
     "legendFormat": "{{ips_returned}}"
    }
   ]
  },
  {
   "title": "DNS Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_dns_responses_total{rcode!=\"No Error\", cluster=~\"$cluster\"}[1m])) by (pod, qtypes, rcode)",
     "legendFormat": "{{rcode}} ({{qtypes}})"
    }
   ]
  },
  {
   "title": "Pods with DNS errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(rate(hubble_dns_responses_total{rcode!=\"No Error\", cluster=~\"$cluster\"}[1m])) by (pod, destination))",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Top 10 DNS Queries per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(hubble_dns_queries_total[10m])*60) by (query, qtypes))",
     "legendFormat": "{{query}} ({{qtypes}})"
    }
   ]
  }
 ]
}