{{- $topology := (lookup "v1" "ConfigMap" .Release.Namespace "yucca-topology") | default dict }}
{{- $topologyData := (get $topology "data") | default dict }}
{{- $_ := set .Values "podAnnotations" (merge
  (dict "yucca.futo.org/topology-checksum" (sha256sum (toJson $topologyData)))
  (.Values.podAnnotations | default dict)) }}
{{- include "yucca-common.deployment" . }}
