#!/usr/bin/env bash
#MISE description="Run yucca-sdk/orchestration-api in development mode"
#MISE depends=["yucca-sdk:orchestration-ui:generate-fetch-client"]
set -e

pnpm --filter @futo-org/backups-orchestrator-api dev
