# Render the ansible/mgmt inventory from TF sources of truth (fabric-addressing,
# identity, mgmt-hosts.yaml). Local provider only, no backend/secrets — runs
# just-in-time via `mise run mgmt:ansible`. Outputs are gitignored.

locals {
  cfg     = yamldecode(file("${path.module}/../../deployment/${var.partition}/${var.region}/mgmt-hosts.yaml"))
  hosts   = local.cfg.hosts
  inv_dir = "${path.module}/../../../ansible/mgmt/inventories/${var.region}"

  pub_mask       = split("/", module.addressing.public_cidr)[1]
  priv_mask      = split("/", module.addressing.private_cidr)[1]
  host_mgmt_mask = split("/", module.addressing.host_mgmt_cidr)[1]
  kube_mask      = split("/", module.addressing.kube_cidr)[1]
  mgmt_mask      = split("/", module.addressing.mgmt_cidr)[1]

  header = "# GENERATED by `mise run mgmt:render-inventory` (tf/render/ansible-mgmt).\n# Do not edit — edit the Terraform sources (mgmt-hosts.yaml, fabric-addressing, identity).\n"
}

module "addressing" {
  source     = "../../shared/modules/fabric-addressing"
  site_id    = local.cfg.site_id
  cluster_id = local.cfg.cluster_id
}

module "identity" {
  source = "../../shared/modules/identity"
}

# Inventory: hosts + public IPs (ansible connects as root over the public IP).
resource "local_file" "hosts" {
  filename = "${local.inv_dir}/hosts.yml"
  content = "${local.header}${yamlencode({
    mgmt = {
      hosts = { for name, h in local.hosts : name => { ansible_host = h.public_ip } }
      vars = {
        ansible_user               = "root"
        ansible_python_interpreter = "/usr/bin/python3"
      }
    }
  })}"
}

# Per-host L3 for forwarding the NetBird-routed site subnets: OOB 1G NIC on the
# mgmt LAN + tagged VLANs on the 25G NIC. Bootstrap over the public IP (site.yml
# reconnects over NetBird once joined).
resource "local_file" "host_vars" {
  for_each = local.hosts
  filename = "${local.inv_dir}/host_vars/${each.key}.yml"
  content = "${local.header}${yamlencode({
    mgmt_public_ip = each.value.public_ip
    mgmt_oob = {
      nic     = each.value.oob_nic
      address = "${cidrhost(module.addressing.mgmt_cidr, each.value.oob_host)}/${local.mgmt_mask}"
    }
    mgmt_fabric_nic = each.value.fabric_nic
    mgmt_fabric_vlans = [
      { id = module.addressing.public_vlan_id, address = "${cidrhost(module.addressing.public_cidr, each.value.host_index)}/${local.pub_mask}" },
      { id = module.addressing.private_vlan_id, address = "${cidrhost(module.addressing.private_cidr, each.value.host_index)}/${local.priv_mask}" },
      { id = module.addressing.host_mgmt_vlan_id, address = "${cidrhost(module.addressing.host_mgmt_cidr, each.value.host_index)}/${local.host_mgmt_mask}" },
      # lb_internal route: mgmt hosts are the NetBird routing peers for the
      # internal LB VIPs; the spine (kube IRB .1) carries the /32s via iBGP.
      { id = module.addressing.kube_vlan_id, address = "${cidrhost(module.addressing.kube_cidr, each.value.host_index)}/${local.kube_mask}", routes = [
        { to = module.addressing.lb_internal_cidr, via = cidrhost(module.addressing.kube_cidr, 1) },
      ] },
    ]
  })}"
}

# group_vars: login users from the identity registry (server-mapped groups).
resource "local_file" "users" {
  filename = "${local.inv_dir}/group_vars/all/users.generated.yml"
  content  = "${local.header}${yamlencode({ mgmt_users = module.identity.server_login })}"
}
