# Render the ansible/mgmt inventory for a site from Terraform's sources of truth:
#   • fabric-addressing — VLAN ids + per-host VLAN addresses
#   • identity          — server login users (+ keys + sudo)
#   • mgmt-hosts.yaml   — the host roster (IPs, NICs, host index, OOB octet)
#
# Lightweight by design (local provider only, no backend/secrets), so it can run
# just-in-time in the ansible CI job (and locally) via `mise run mgmt:ansible`.
# Outputs are gitignored — TF is the single source of truth, not the rendered files.

locals {
  cfg     = yamldecode(file("${path.module}/../../deployment/prod/${var.site}/mgmt-hosts.yaml"))
  hosts   = local.cfg.hosts
  inv_dir = "${path.module}/../../../ansible/mgmt/inventories/${var.site}"

  pub_mask  = split("/", module.addressing.public_cidr)[1]
  priv_mask = split("/", module.addressing.private_cidr)[1]
  api_mask  = split("/", module.addressing.api_cidr)[1]
  mgmt_mask = split("/", module.addressing.mgmt_cidr)[1]

  header = "# GENERATED by `mise run mgmt:render-inventory` (tf/render/ansible-mgmt).\n# Do not edit — edit the Terraform sources (mgmt-hosts.yaml, fabric-addressing, identity).\n"
}

module "addressing" {
  source     = "../../shared/modules/fabric-addressing"
  site_id    = local.cfg.site_id
  cluster_id = local.cfg.cluster_id
}

module "identity" {
  source = "../../shared/modules/identity"
}

# Inventory: hosts + public IPs (ansible connects as root over the public IP).
resource "local_file" "hosts" {
  filename = "${local.inv_dir}/hosts.yml"
  content = "${local.header}${yamlencode({
    mgmt = {
      hosts = { for name, h in local.hosts : name => { ansible_host = h.public_ip } }
      vars = {
        ansible_user               = "root"
        ansible_python_interpreter = "/usr/bin/python3"
      }
    }
  })}"
}

# Per-host L3 so the node can forward the NetBird-routed site subnets:
#   • OOB 1G NIC on the management LAN (10.40.5.0/24 — the switch vme)
#   • tagged VLAN sub-interfaces on the 25G NIC (public/private/api)
# Addresses/ids come from the addressing module; bootstrap is the public IP
# (site.yml reconnects over NetBird once the host joins).
resource "local_file" "host_vars" {
  for_each = local.hosts
  filename = "${local.inv_dir}/host_vars/${each.key}.yml"
  content = "${local.header}${yamlencode({
    mgmt_public_ip = each.value.public_ip
    mgmt_oob = {
      nic     = each.value.oob_nic
      address = "${cidrhost(module.addressing.mgmt_cidr, each.value.oob_host)}/${local.mgmt_mask}"
    }
    mgmt_fabric_nic = each.value.fabric_nic
    mgmt_fabric_vlans = [
      { id = module.addressing.public_vlan_id, address = "${cidrhost(module.addressing.public_cidr, each.value.host_index)}/${local.pub_mask}" },
      { id = module.addressing.private_vlan_id, address = "${cidrhost(module.addressing.private_cidr, each.value.host_index)}/${local.priv_mask}" },
      { id = module.addressing.api_vlan_id, address = "${cidrhost(module.addressing.api_cidr, each.value.host_index)}/${local.api_mask}" },
    ]
  })}"
}

# group_vars: login users from the identity registry (server-mapped groups).
resource "local_file" "users" {
  filename = "${local.inv_dir}/group_vars/all/users.generated.yml"
  content  = "${local.header}${yamlencode({ mgmt_users = module.identity.server_login })}"
}
