apiVersion: v2
name: yucca-admin-api
description: Yucca admin API (NestJS)
type: application
version: 0.1.0
appVersion: "0.0.1"
dependencies:
  - name: yucca-common
    version: 0.1.0
    repository: "file://../yucca-common"
