# Password items per cluster (<CLUSTER>_CEPH_OPS_PASSWORD, _DASHBOARD_PASSWORD,
# _GRAFANA_PASSWORD). Titles come from the ceph-cluster module's `secrets`
# output; values are generated by password_recipe (32-char alphanumeric). The
# onepassword provider authenticates via OP_SERVICE_ACCOUNT_TOKEN -- infra.yml
# apply uses the write SA OP_TF_YUCCA_STAGING_ENV_WRITE; local runs export a
# superuser SA token.
#
# Stack-level (not in the shared module) so dev/ceph, which does not manage
# secrets in TF, never pulls in the onepassword provider. Mirrors
# tf/deployment/staging/talos/secrets.tf.
#
# NOT created here, by design:
#   - S3 svc-user keys (<CLUSTER>_CEPH_S3_SVC_YUCCA_RESTIC_{ACCESS,SECRET}_KEY):
#     the stable contract with the immich/restic consumer (staging/talos), which
#     already reads them from yucca_tf_staging. They are provisioned out-of-band
#     and must keep stable values -- the rebuilt RGW is seeded from the same
#     items, so recreating them here would collide and churn a live contract.
#   - SSH Key item (<CLUSTER>_CEPH_ANSIBLE_IAC_SSH_KEY): generated via op CLI
#     `--ssh-generate-key` per ADR-010 (provider can't generate inline; import
#     would put the private key in state).
#   - DR Document items (RGW TLS cert/key, admin keyring): captured post-deploy
#     by `mise run capture`.

locals {
  # Secret roles owned by the immich/restic contract, provisioned out-of-band.
  # Excluded from TF management here (see header).
  ceph_unmanaged_secret_roles = ["s3_restic_access", "s3_restic_secret"]

  # Flatten (cluster, secret-role) -> { vault, title } across all clusters,
  # dropping the out-of-band roles.
  ceph_secret_items = merge([
    for cname, c in var.clusters : {
      for role, title in module.cluster[cname].secrets :
      "${cname}.${role}" => {
        vault = coalesce(c.vault, "Yucca")
        title = title
      }
      if !contains(local.ceph_unmanaged_secret_roles, role)
    }
  ]...)
}

data "onepassword_vault" "target" {
  for_each = toset([for c in var.clusters : coalesce(c.vault, "Yucca")])
  name     = each.value
}

resource "onepassword_item" "ceph_password" {
  for_each = local.ceph_secret_items

  vault    = data.onepassword_vault.target[each.value.vault].uuid
  title    = each.value.title
  category = "password"

  password_recipe {
    length  = 32
    letters = true
    digits  = true
    symbols = false
  }

  lifecycle {
    # Rotating a value should be an explicit `terragrunt taint` + apply, not an
    # incidental side effect of editing the recipe.
    ignore_changes = [password_recipe]
  }
}
