name: Git Town

on:
  pull_request:

jobs:
  git-town:
    name: Display the branch stack
    runs-on: ubuntu-slim

    if: ${{ !startsWith(github.head_ref, 'release-please--') }}

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: git-town/action@670e1f4feb81fdef4226fc09deefe09018eb20d1 # v1.3.3
